#! /bin/sh

PROCESS_ID=$(ps x | grep 'node -r dotenv/config .output/server/index.mjs' | grep -v grep | awk '{print $1}')
if [ ! -z "$PROCESS_ID" ];
then
    pkill -9 -f 'node -r dotenv/config .output/server/index.mjs'
else
    echo "Server is not running"
fi
