#! /bin/sh

if [ ! -f server.pid ];
then
    pnpm i
    nohup pnpm cross-env NODE_ENV=production ts-node-dev src/revite-server.ts > log/$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 & echo $! > server.pid
    nohup pnpm prisma studio > /dev/null 2>&1 & echo $! > prisma.pid
else
    echo "Server is already running"
fi
