#! /bin/sh

PROCESS_ID=$(ps x | grep 'node dist/revite-server.js' | grep -v grep | awk '{print $1}')
if [ ! -z "$PROCESS_ID" ];
then
    pkill -9 -f 'node dist/revite-server.js'
else
    echo "Server is not running"
fi
